CREATE SEQUENCE seq_tarefa START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_sub_tarefa START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE TAREFA (
  ID_TAREFA        NUMBER(19)      NOT NULL,
  TITULO_TAREFA    VARCHAR2(150)   NOT NULL,
  DESCRICAO        VARCHAR2(1000),
  DATA_VENCIMENTO  DATE            NOT NULL,
  STATUS           VARCHAR2(20)    NOT NULL,
  PRIORIDADE       VARCHAR2(20)    NOT NULL,
  CONSTRAINT PK_TAREFA PRIMARY KEY (ID_TAREFA),
  CONSTRAINT UK_TAREFA_TITULO UNIQUE (TITULO_TAREFA),
  CONSTRAINT CK_TAREFA_STATUS CHECK (STATUS IN ('PENDENTE','EM_ANDAMENTO','CONCLUIDA','CANCELADA')),
  CONSTRAINT CK_TAREFA_PRIORIDADE CHECK (PRIORIDADE IN ('BAIXA','MEDIA','ALTA'))
);


CREATE TABLE SUB_TAREFA (
  ID_SUB_TAREFA    NUMBER(19)    NOT NULL,
  TITULO_SUB_TAREFA VARCHAR2(150) NOT NULL,
  STATUS           VARCHAR2(20)  NOT NULL,
  ID_TAREFA        NUMBER(19)    NOT NULL,
  CONSTRAINT PK_SUB_TAREFA PRIMARY KEY (ID_SUB_TAREFA),
  CONSTRAINT FK_SUB_TAREFA_TAREFA FOREIGN KEY (ID_TAREFA)
    REFERENCES TAREFA (ID_TAREFA) ON DELETE CASCADE,
  CONSTRAINT CK_SUB_TAREFA_STATUS CHECK (STATUS IN ('PENDENTE','EM_ANDAMENTO','CONCLUIDA','CANCELADA'))
);