INSERT INTO TAREFA (ID_TAREFA, TITULO_TAREFA, DESCRICAO, DATA_VENCIMENTO, STATUS, PRIORIDADE)
VALUES (seq_tarefa.NEXTVAL, 'Planejar backlog', 'Organizar as histórias do próximo sprint',
        DATE '2025-08-20', 'PENDENTE', 'ALTA');

INSERT INTO TAREFA (ID_TAREFA, TITULO_TAREFA, DESCRICAO, DATA_VENCIMENTO, STATUS, PRIORIDADE)
VALUES (seq_tarefa.NEXTVAL, 'Implementar API de tarefas', 'Endpoints CRUD com validações',
        DATE '2025-08-22', 'EM_ANDAMENTO', 'MEDIA');

INSERT INTO TAREFA (ID_TAREFA, TITULO_TAREFA, DESCRICAO, DATA_VENCIMENTO, STATUS, PRIORIDADE)
VALUES (seq_tarefa.NEXTVAL, 'Escrever testes', 'Cobrir services e controllers',
        DATE '2025-08-25', 'PENDENTE', 'ALTA');

INSERT INTO TAREFA (ID_TAREFA, TITULO_TAREFA, DESCRICAO, DATA_VENCIMENTO, STATUS, PRIORIDADE)
VALUES (seq_tarefa.NEXTVAL, 'Configurar CI', 'Build, testes e análise estática',
        DATE '2025-08-28', 'PENDENTE', 'BAIXA');


INSERT INTO SUB_TAREFA (ID_SUB_TAREFA, TITULO_SUB_TAREFA, STATUS, ID_TAREFA)
VALUES (seq_sub_tarefa.NEXTVAL, 'Criar endpoint POST /tarefas', 'EM_ANDAMENTO', 2);

INSERT INTO SUB_TAREFA (ID_SUB_TAREFA, TITULO_SUB_TAREFA, STATUS, ID_TAREFA)
VALUES (seq_sub_tarefa.NEXTVAL, 'Validar regra de conclusão', 'PENDENTE', 2);

INSERT INTO SUB_TAREFA (ID_SUB_TAREFA, TITULO_SUB_TAREFA, STATUS, ID_TAREFA)
VALUES (seq_sub_tarefa.NEXTVAL, 'Pipeline de testes', 'PENDENTE', 4);